---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nft-bridge
  template:
    metadata:
      labels:
        app: nft-bridge
    spec:
      containers:
        - name: devops-container
          image:  $ECR_REPOSITORY:$BUILD_NUMBER
          ports:
             - containerPort: 3000
               protocol: TCP

